"""
Gemini Client for AI-assisted security analysis and Assistant chat.

# HTTP Client (httpx) — an asynchronous library used to send REST requests to external AI APIs.
# Rate Limiting / 429 — an HTTP status code sent by an API when you exceed your request quota.
"""

import os
import json
from typing import Optional, Dict, Any, Tuple
import httpx

from backend.core.config import settings
from backend.core.logging import logger, redact_secrets


class GeminiClient:
    """
    Communicates with Google Gemini models via Gemini's OpenAI-compatible or REST endpoint.
    Handles quota exhaustion (HTTP 429) detection and formatted security queries.
    """

    def __init__(self):
        self.api_base = settings.GEMINI_API_BASE
        self.model = settings.GEMINI_MODEL
        # Remove 'openai/' prefix if present for direct model references
        self.clean_model_name = self.model.replace("openai/", "")
        self.api_key = self._resolve_api_key()

    def _resolve_api_key(self) -> Optional[str]:
        """
        Safely resolves the Gemini API key from settings, environment,
        or ~/.strix/cli-config.json.
        """
        if settings.GEMINI_API_KEY:
            return settings.GEMINI_API_KEY
        if os.environ.get("GEMINI_API_KEY"):
            return os.environ.get("GEMINI_API_KEY")
        if os.environ.get("LLM_API_KEY"):
            return os.environ.get("LLM_API_KEY")

        # Fallback check into ~/.strix/cli-config.json where Strix stores its active key
        strix_cfg_path = os.path.expanduser("~/.strix/cli-config.json")
        if os.path.exists(strix_cfg_path):
            try:
                with open(strix_cfg_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    env_dict = data.get("env", {})
                    key = env_dict.get("LLM_API_KEY")
                    if key:
                        return key
            except Exception as e:
                logger.debug(f"Could not read key from strix config: {e}")
        return None

    async def check_health(self) -> Tuple[bool, str]:
        """
        Checks if Gemini is reachable and has a configured API key.
        """
        if not self.api_key:
            return False, "API key not configured"
        try:
            # Quick lightweight health check probe
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            }
            url = f"{self.api_base.rstrip('/')}/models"
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.get(url, headers=headers)
                if resp.status_code == 200:
                    return True, "Available"
                elif resp.status_code == 429:
                    return False, "Quota Exceeded (HTTP 429)"
                elif resp.status_code == 401:
                    return False, "Invalid API Key"
                else:
                    return True, f"Online (HTTP {resp.status_code})"
        except Exception as exc:
            return False, f"Connection error: {str(exc)}"

    async def generate_response(
        self, prompt: str, system_prompt: Optional[str] = None
    ) -> Tuple[bool, str, Optional[int]]:
        """
        Sends a query to Gemini and returns:
        (success: bool, content_or_error: str, status_code: Optional[int])
        """
        if not self.api_key:
            return False, "Gemini API key is not configured.", 401

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.clean_model_name,
            "messages": messages,
            "temperature": 0.2,
        }

        url = f"{self.api_base.rstrip('/')}/chat/completions"

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(url, headers=headers, json=payload)
                
                if response.status_code == 200:
                    data = response.json()
                    choices = data.get("choices", [])
                    if choices:
                        content = choices[0].get("message", {}).get("content", "")
                        return True, content, 200
                    return True, "No response generated by model.", 200
                
                error_msg = redact_secrets(response.text)
                return False, f"HTTP {response.status_code}: {error_msg}", response.status_code

        except httpx.TimeoutException:
            return False, "Gemini request timed out after 30 seconds.", 408
        except Exception as exc:
            return False, f"Gemini connection failure: {redact_secrets(str(exc))}", 500
