"""
Strix Adapter — High-level interface connecting the Strix engine to the platform's database and API.

# Adapter Pattern — an architectural design pattern that translates the interface of an external tool (Strix) into an interface expected by our application.
# Data Ingestion — reading and standardizing scan files generated by external tools into local database records.
"""

import os
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.core.config import settings
from backend.core.logging import logger
from backend.database.connection import AsyncSessionLocal
from backend.database.models import (
    Scan,
    Finding,
    ScanLog,
    AttackPathNode,
    AttackPathEdge,
    Project,
)
from backend.integrations.strix.strix_parser import parse_strix_run_directory
from backend.integrations.strix.strix_runner import (
    execute_strix_scan,
    cancel_active_scan,
    resolve_strix_executable,
)


class StrixAdapter:
    """
    Coordinates scan execution, background task handling, and database synchronization.
    """

    async def start_scan_job(
        self,
        scan_id: str,
        target: str,
        scan_mode: str = "deep",
        instruction: Optional[str] = None,
        max_budget: Optional[float] = None,
        max_turns: Optional[int] = None,
        resume_run_name: Optional[str] = None,
    ) -> None:
        """
        Launches Strix scan execution as a background asyncio task.
        """
        async def on_log_callback(s_id: str, level: str, msg: str):
            # Save log line asynchronously to database
            async with AsyncSessionLocal() as session:
                log_row = ScanLog(
                    scan_id=s_id,
                    timestamp=datetime.utcnow(),
                    level=level,
                    message=msg,
                    source="strix",
                )
                session.add(log_row)
                await session.commit()

        async def on_complete_callback(s_id: str, exit_code: int, run_name: Optional[str], status: str, provider: Optional[str] = None):
            logger.info(f"Scan {s_id} finished with status '{status}' (code {exit_code})")
            async with AsyncSessionLocal() as session:
                res = await session.execute(select(Scan).where(Scan.id == s_id))
                scan_row = res.scalar_one_or_none()
                if scan_row:
                    scan_row.status = status
                    scan_row.exit_code = exit_code
                    scan_row.end_time = datetime.utcnow()
                    if provider:
                        scan_row.provider_used = provider
                    if scan_row.start_time:
                        scan_row.elapsed_seconds = int(
                            (scan_row.end_time - scan_row.start_time).total_seconds()
                        )
                    if run_name:
                        scan_row.strix_run_name = run_name

                    await session.commit()

                    # Find output run directory and parse SARIF findings
                    await self._ingest_scan_results(session, scan_row)

        # Fire and forget background task
        asyncio.create_task(
            execute_strix_scan(
                scan_id=scan_id,
                target=target,
                scan_mode=scan_mode,
                instruction=instruction,
                max_budget=max_budget,
                max_turns=max_turns,
                resume_run_name=resume_run_name,
                on_log_callback=on_log_callback,
                on_complete_callback=on_complete_callback,
            )
        )

    async def _ingest_scan_results(self, session: AsyncSession, scan: Scan) -> None:
        """
        Locates the Strix run folder, parses SARIF 2.1.0 findings, and stores them in the database.
        """
        # Search for run folder matching run_name or scan_id in SCANS_RUN_DIR and discover dirs
        candidate_dirs = [settings.SCANS_RUN_DIR] + settings.DISCOVERY_RUNS_DIRS
        target_dir = None

        for base in candidate_dirs:
            if not os.path.isdir(base):
                continue
            for item in os.listdir(base):
                item_path = os.path.join(base, item)
                if not os.path.isdir(item_path):
                    continue
                if (scan.strix_run_name and item == scan.strix_run_name) or (scan.id[:8] in item):
                    target_dir = item_path
                    break
            if target_dir:
                break

        if not target_dir:
            logger.warning(f"Could not locate run output directory for scan {scan.id}")
            return

        metadata, findings, coverage = parse_strix_run_directory(target_dir)

        if metadata and not scan.strix_run_name:
            scan.strix_run_name = metadata.run_name

        scan.raw_summary = {
            "metadata": metadata.dict() if metadata else None,
            "coverage": coverage,
            "findings_count": len(findings),
        }

        # Insert findings
        for f_item in findings:
            finding_row = Finding(
                scan_id=scan.id,
                project_id=scan.project_id,
                title=f_item.title,
                severity=f_item.severity,
                category=f_item.category,
                description=f_item.description,
                location=f_item.location,
                endpoint=f_item.endpoint,
                evidence=f_item.evidence,
                impact=f_item.impact,
                recommendation=f_item.recommendation,
                status="Open",
            )
            session.add(finding_row)

        # Generate attack path nodes & edges if findings correlate to endpoints
        await self._build_attack_paths(session, scan.id, findings)
        await session.commit()
        logger.info(f"Ingested {len(findings)} findings for scan {scan.id}")

    async def _build_attack_paths(self, session: AsyncSession, scan_id: str, findings: List[Any]) -> None:
        """
        Constructs correlated attack path nodes and edges from findings where evidence permits.
        Never fabricates relationships without supporting data.
        """
        # If findings exist, create nodes for entry points, vulnerabilities, and target resources
        if not findings:
            return

        entry_node = AttackPathNode(
            scan_id=scan_id,
            node_id=f"entry_{scan_id[:8]}",
            label="External Attack Surface",
            node_type="entry_point",
        )
        session.add(entry_node)

        for idx, f in enumerate(findings):
            vuln_node_id = f"vuln_{scan_id[:8]}_{idx}"
            vuln_node = AttackPathNode(
                scan_id=scan_id,
                node_id=vuln_node_id,
                label=f.title[:50],
                node_type="vulnerability",
                metadata_json={"severity": f.severity, "category": f.category},
            )
            session.add(vuln_node)

            # Edge from Entry Point to Vulnerability
            session.add(
                AttackPathEdge(
                    scan_id=scan_id,
                    source_id=entry_node.node_id,
                    target_id=vuln_node_id,
                    relation_type="reaches",
                    evidence=f.location,
                )
            )

            # If an endpoint is affected, add an endpoint node
            if f.endpoint:
                ep_node_id = f"ep_{scan_id[:8]}_{idx}"
                ep_node = AttackPathNode(
                    scan_id=scan_id,
                    node_id=ep_node_id,
                    label=f.endpoint[:50],
                    node_type="endpoint",
                )
                session.add(ep_node)
                session.add(
                    AttackPathEdge(
                        scan_id=scan_id,
                        source_id=vuln_node_id,
                        target_id=ep_node_id,
                        relation_type="affects_endpoint",
                        evidence=f.evidence,
                    )
                )

    async def discover_and_import_existing_runs(self) -> int:
        """
        Scans discovery directories (such as SignBridgeAI/strix_runs) and automatically
        imports existing historical scans so the user can immediately view and compare real data.
        """
        imported_count = 0
        async with AsyncSessionLocal() as session:
            for base_dir in settings.DISCOVERY_RUNS_DIRS:
                if not os.path.exists(base_dir) or not os.path.isdir(base_dir):
                    continue

                for entry in os.listdir(base_dir):
                    run_dir = os.path.join(base_dir, entry)
                    if not os.path.isdir(run_dir):
                        continue

                    # Check if run.json exists
                    if not os.path.exists(os.path.join(run_dir, "run.json")):
                        continue

                    run_name = entry
                    # Check if already imported
                    res = await session.execute(
                        select(Scan).where(Scan.strix_run_name == run_name)
                    )
                    existing = res.scalar_one_or_none()
                    if existing:
                        continue

                    # Parse run directory
                    metadata, findings, coverage = parse_strix_run_directory(run_dir)
                    if not metadata:
                        continue

                    target_val = "Unknown Target"
                    target_type = "local_project"
                    if metadata.targets_info:
                        t_info = metadata.targets_info[0]
                        target_val = t_info.get("original") or t_info.get("details", {}).get("target_path", "Local Target")
                        t_type_raw = t_info.get("type", "local_code")
                        if "repo" in t_type_raw:
                            target_type = "github_repo"
                        elif "url" in t_type_raw:
                            target_type = "web_app"

                    # Create Project if not exists
                    proj_name = Path(target_val).name or run_name
                    res_p = await session.execute(select(Project).where(Project.name == proj_name))
                    proj = res_p.scalar_one_or_none()
                    if not proj:
                        proj = Project(
                            name=proj_name,
                            description=f"Discovered application from Strix run {run_name}",
                            target_type=target_type,
                            target_value=target_val,
                        )
                        session.add(proj)
                        await session.flush()

                    # Create Scan record
                    start_dt = None
                    if metadata.start_time:
                        try:
                            start_dt = datetime.fromisoformat(metadata.start_time.replace("Z", "+00:00"))
                        except Exception:
                            start_dt = datetime.utcnow()

                    end_dt = None
                    if metadata.end_time:
                        try:
                            end_dt = datetime.fromisoformat(metadata.end_time.replace("Z", "+00:00"))
                        except Exception:
                            end_dt = datetime.utcnow()

                    scan_row = Scan(
                        project_id=proj.id,
                        target_type=target_type,
                        target_value=target_val,
                        scan_mode="deep",
                        status="Completed" if metadata.status in ["completed", "running"] else metadata.status.capitalize(),
                        start_time=start_dt,
                        end_time=end_dt,
                        strix_run_name=run_name,
                        provider_used="GEMINI",
                        exit_code=0,
                        raw_summary={"metadata": metadata.dict(), "coverage": coverage},
                    )
                    session.add(scan_row)
                    await session.flush()

                    # Ingest findings
                    for f in findings:
                        finding_row = Finding(
                            scan_id=scan_row.id,
                            project_id=proj.id,
                            title=f.title,
                            severity=f.severity,
                            category=f.category,
                            description=f.description,
                            location=f.location,
                            endpoint=f.endpoint,
                            evidence=f.evidence,
                            impact=f.impact,
                            recommendation=f.recommendation,
                            status="Open",
                        )
                        session.add(finding_row)

                    await self._build_attack_paths(session, scan_row.id, findings)
                    imported_count += 1
                    logger.info(f"Imported discovered Strix run: {run_name} ({len(findings)} findings)")

            if imported_count > 0:
                await session.commit()

        return imported_count


# Global Strix adapter instance
strix_adapter = StrixAdapter()
